version: '3'

services:
  zinc:
    image: "public.ecr.aws/zinclabs/zinc:latest"
    container_name: "zinc"
    ports: 
    - "4080:4080"
    volumes:
    - ./data:/data

    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: Complexpass#123
      ZINC_DATA_PATH: "/data"

